from typing import Any

class FileSystemEventHandler:
    def on_any_event(self, event: Any) -> None: ...
    def on_moved(self, event: Any) -> None: ...
    def on_created(self, event: Any) -> None: ...
    def on_deleted(self, event: Any) -> None: ...
    def on_modified(self, event: Any) -> None: ...
